openapi: 3.1.0
info:
   title: API сервер для проекта «Шесть городов(простой)».
   description: |-
     * Список ресурсов и маршрутов сервера «Шесть городов(простой)».
   license:
     name: MIT
     url: https://opensource.org/licenses/MIT
   version: 2.0.0

tags:
  - name: offers
    description: Действия с объявлениями.
  - name: comments
    description: Действия с комментариями.
  - name: users
    description: Действия с пользователем.

paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя.
      requestBody:
         description: Информация для создания нового пользователя.
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/createUser'
         required: true

      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userCreated'

        "409":
          description: Пользователь с таким email уже существует.

  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/loginUser'
      required: true

      responses:
        "200":
          description: Пользователь завторизован. Токен пользователя.
          security:
            - SessionToken: []

        "401":
          description: Неправильный логин или пароль.

        "404":
          description: Пользователь не найден.

  /users/user-check:
    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю
      security:
        - SessionToken: []

      responses:
        "200":
          description: Пользователь авторизован.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userValid'

        "401":
          description: Пользователь не авторизован.

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя. Изображение
        аватара должно быть в формате `png` или `jpg`.
      security:
        - SessionToken: []

      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer

      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
                  description: The user avatar image file to be uploaded

      responses:
        201:
          description: Avatar uploaded successfully
        400:
          description: Bad request
        401:
          description: Unauthorized

  /offers:
    get:
      tags:
        - offers
      summary: Получить список объявлений
      description: Получает список всех объявлений.
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            example: 1

      responses:
         "200":
           description: Список предложений.
           content:
             application/json:
              type: array
              items:
                $ref: '#/components/schemas/offersListItem'

    post:
      tags:
        - offers
      summary: Создать объявление
      description: Создает новое объявление.
      requestBody:
        description: Информация для создания нового предложения.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createOffer'
        required: true

      responses:
        "200":
          description: Объявление создано успешно.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/createOffer'
                  - $ref: '#/components/schemas/commentCounter'

        "401":
          description: Для размещения объявления, пользователь должен быть авторизован.

        "400":
          description: Не заполнены обязательные поля.

  /offers/{offerId}:
    patch:
      tags:
        - offers
      summary: Редактирование объявления
      description: Редактирует выбранное объявление и возвращает в качестве ответа
        обновленный объект объявления.
      parameters:
        - in: path
          name: offerId
          required: true
          schema:
            type: integer

      requestBody:
        description: Информация для редактирования предложения.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createOffer'
        required: true

      responses:
        "200":
          description: Отредактированное предложение по аренде.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/createOffer'
                  - $ref: '#/components/schemas/commentCounter'

        "400":
          description: Незаполненны обязательные поля.

        "401":
          description: Пользователь должен быть авторизован.

        "403":
          description: У пользователя нет прав редактировать данное предложение по аренде.

        '404':
          description: Предложение по аренде не найдено.

    delete:
      tags:
        - offers
      summary: Удаление объявления
      description: Удаляет выбранное объявление и все связанные с ним комментарии.
      parameters:
        - in: path
          name: offerId
          required: true
          schema:
            type: integer

      responses:
         "200":
           description: Предложение по аренде удалено.

         "401":
           description: Пользователь должен быть авторизован.

         "403":
           description: У пользователя нет прав редактировать данное предложение по аренде.

         "404":
           description: Предложение по аренде не найдено.

    get:
      tags:
        - offers
      summary: Получение информации по одному объявлению.
      description: Получение детальной информации по одному объявлению.
      parameters:
        - in: path
          name: offerId
          required: true
          schema:
            type: integer

      responses:
        "200":
          description: Информация о предложений.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/createOffer'
                  - $ref: '#/components/schemas/commentCounter'

  /comments:
    get:
      tags:
        - comments
      summary: Список комментариев объявления
      description: Получение списка комментариев для определенного объявления.
      parameters:
        - in: query
          name: offerId
          required: true
          schema:
            type: integer
            example: 1

      responses:
         "200":
           description: Список комментариев.
           content:
             application/json:
              type: array
              items:
                allOf:
                  - $ref: '#/components/schemas/comment'
                  - $ref: '#/components/schemas/commentDate'

    post:
      tags:
        - comments
      summary: Добавление комментария
      description: Добавление комментария к определенному объявлению.
      parameters:
        - in: query
          name: offerId
          required: true
          schema:
            type: integer
            example: 1

      requestBody:
        description: Информация для создания нового комментария.
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/comment'
        required: true

      responses:
        "200":
          description: Комментарий создан, присылаю его в ответ.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/comment'
                  - $ref: '#/components/schemas/commentDate'

        "401":
          description: Для размещения комментария, пользователь должен быть авторизован.

        "400":
          description: Незаполненны обязательные поля.

securityDefinitions:
  SessionToken:
    type: apiKey
    name: X-Session-Token
    in: header

components:
  schemas:
    createUser:
      type: object

      properties:
        username:
          type: string
          example: Keks

        email:
          type: string
          example: keks@htmlacademy.ru

        password:
          type: string
          example: qwerty12345

    userCreated:
      type: object

      properties:
        username:
          type: string
          example: Keks

        email:
          type: string
          example: keks@htmlacademy.ru

        isPro:
          type: boolean
          example: false

        avatarPath:
          type: string
          example: torrance.png

    userValid:
      type: object

      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea

        username:
          type: string
          example: Keks

        email:
          type: string
          example: keks@htmlacademy.ru

        isPro:
          type: boolean
          example: false

        avatarPath:
          type: string
          example: torrance.png

    loginUser:
      type: object

      properties:
        email:
          type: string
          example: keks@htmlacademy.ru

        password:
          type: string
          example: qwerty12345

    offersListItem:
      type: object

      properties:
        title:
          type: string
          example: Property name

        createdAt:
           type: Date
           example: 10.12.22

        offerType:
          type: string
          example: apartment

        city:
          type: string
          $ref: '#/components/schemas/city'

        price:
          type: number
          example: 1500

        thumbnail:
          type: string
          example: imagePath

        isPremium:
          type: boolean
          example: false

        rating:
          type: number
          example: 3.7

        commentsCounter:
          type: number
          example: 3

    createOffer:
      type: object

      properties:
        title:
          type: string
          example: Property name

        description:
          type: string
          example: Property description

        createdAt:
          type: Date
          example: 10.12.22

        city:
          type: string
          example: Paris

        thumbnail:
          type: string
          example: imagePath

        pictures:
          type: array
          items:
            type: string
            example: imagePath

        isPremium:
          type: boolean
          example: false

        rating:
          type: number
          example: 3.7

        offerType:
          type: string
          example: apartment

        rooms:
          type: number
          example: 3

        guests:
          type: number
          example: 3

        price:
          type: number
          example: 1500

        conveniences:
          type: array
          items:
            type: string
            example: bathroom

        userId:
          type: string
          example: testId

        location:
          $ref: '#/components/schemas/location'

    commentCounter:
      type: number
      example: 15

    commentDate:
      type: Date
      example: 23.10.22

    comment:
      type: object

      properties:
        text:
          type: string
          example: text comment

        rating:
          type: number
          example: 3

        author:
          type: string
          example: Valik

    uploadAvatar:
      type: object

      properties:
        images:
          type: string
          format: binary

        required:
          - image

    location:
      type: object
      properties:
        latitude:
          type: number
          example: 48.85661
        longitude:
          type: number
          example: 2.351499

    city:
      type: object
      properties:
        name:
          type: string
          example: Paris
        location:
          $ref: '#/components/schemas/location'
















